### ISSUE TITLE
Support transfers to ECAL DQM

### ISSUE THREAD

**Issue by janveverka** [smpro/transfer-hook#9]
Transfer DQM streams taken by ECAL in minidaq to the ECAL DQM machine at Point 5. The streams to transfer are DQM and DQMHistograms. The destination should be srv-s2f19-29-01.cms:/dqmminidaq. This was requested by Rafael T DL on May 6, 2015.

This should only happen for runs taken by ECAL. There is currently no support for finding this info out in the transfer hook. The WBM seems to have the info about the used components, e.g. at https://cmswbm.web.cern.ch/cmswbm/cmsdb/runSummary/RunSummary.html

Perhaps this could be also inferred from the HLT key. For example, it is /minidaq/EcalCalibration/v6.0/EcalCalibration_MiniDAQ/V4 for run 239909. One could parse "minidaq" and "EcalCalibration" out of it.

**Comment by zdemirag** [comment]
It looks like none of this is needed.  The minidaq transfers for DQM stream was working until we made the switch from mergers to transfers for the transfer of DQM streams. 

It turns out that DQM has a system that when they receive a DQM file they distribute it to the relevant subsystems. So when we set up the new machine for minidaq (and send the DQM files to DQM), ECAL will receive their files automatically through DQM.

**Comment by zdemirag** [comment]
This is to confirm that we can close the issue!
We have set up srv-C2C07-16  to be the minidaq transfer machine.
We have transferred all the minidaq runs taken so far. 

I belive ECAL has run a test minidaq run: 246181
We transferred it to DQM and after checking the
ecal minidaq dqm area: srv-s2f19-29-01: /dqmminidaq/run246181
we confirm that ECAL can see the run in their area!

[1]
Run    Run Key
246181 TIER0_TRANSFER_OFF
Run    CMSSW_VERSION
246181 CMSSW_7_3_2_patch2
Run    HLT Key
246181 /minidaq/EcalCalibration/v6.0/EcalCalibration_MiniDAQ/V4
Run    Stop Time
246181 5/29/15 12:14:31 PM UTC
Run    Start Time
246181 5/29/15 12:12:42 PM UTC
